ARG HARBOR_URL=nbu-harbor.gtm.nvidia.com
ARG ARCH=x86_64
FROM $HARBOR_URL/hpcx/x86_64/rhel8.6/core:latest
ARG WEBREPO_URL=webrepo.gtm.nvidia.com

RUN sed -i "s/webrepo/${WEBREPO_URL}/" /etc/yum.repos.d/* && \
    sed -i 's/mirrorlist/#mirrorlist/;s!#baseurl=http://mirror.centos.org!baseurl=http://vault.centos.org!' /etc/yum.repos.d/* && \
    echo "[mlnx-opt]" > /etc/yum.repos.d/mlnx-opt.repo && \
    echo "name=RHEL 8.6 mirror" >> /etc/yum.repos.d/mlnx-opt.repo && \
    echo "baseurl=http://${WEBREPO_URL}/RH/optional/8.6/x86_64/" >> /etc/yum.repos.d/mlnx-opt.repo && \
    echo "enabled=1" >> /etc/yum.repos.d/mlnx-opt.repo && \
    echo "gpgcheck=0" >> /etc/yum.repos.d/mlnx-opt.repo && \
    yum makecache

RUN yum install --allowerasing -y \
    java-11-openjdk jq git && \
    yum clean all && \
    rm -rf /var/cache/yum    
